# Generated by Django 4.1.6 on 2023-02-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='movies/posters/')),
                ('duration_min', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=255)),
            ],
        ),
    ]
